### ISSUE TITLE
Android 10 install error

### ISSUE THREAD

**Issue by rsssxd** [accrescent/accrescent#12]
First of all I would like to thank the developers for developing such an application.

I'm using Android 10 (Lineageos) and the first version is giving package error.

**Comment by ghost** [comment]
This app is extremely far from being ready and is still on the drawing board.

It's not ready for even alpha testing yet.

**Comment by lberrymage** [comment]
> First of all I would like to thank the developers for developing such an application.
> 
> I'm using Android 10 (Lineageos) and the first version is giving package error.

Hi reyis4402! I appreciate your interest in Accrescent, but like June said, there's still a ton of work to be done before it's ready for everyday use. Perhaps I should clarify that in the README more.

Regarding the error you're getting, Accrescent only runs on Android 12 and up. Lower versions _may_ be supported in the future, but since Accrescent is still in very early development stages, that's not a priority and it won't be for a while.

**Comment by rsssxd** [comment]
Most of the users today are using Android 10 and 11. At least it could have Android 10 and Android 11 support.

Android 12 is still new and very few app developers will want to support an app store that only works on Android 12.

**Comment by lberrymage** [comment]
I'm aware of how few devices run Android 12 right now and I will take older Android version support into consideration as the project matures. However, Accrescent uses an Android 12 API to perform unprivileged, unattended upgrades, and the app is built around the assumption that that API is available. Because of this assumption, additional logic and/or testing will be needed to support lower versions of Android, and I don't have the bandwidth to work on that since the project has a lot of higher priority work at the moment.

**Comment by ghost** [comment]
It makes sense to target only Android 12 at the moment when the app store is completely brand new.

GrapheneOS is doing the same thing. There's no reason to focus on compatibility when the product isn't even finished yet.

**Comment by rsssxd** [comment]
If GrapheneOS does this, offer an application that can be used safely by other Android users, unlike him.

Supporting Android 10 and 11 is not a bad thing and nothing is lost.

**Comment by rsssxd** [comment]
If GrapheneOS is already doing this, it doesn't make sense to repeat what GrapheneOS did.

**Comment by lberrymage** [comment]
Multiple versions of Android _will_ be supported in the future. But right now spending development time on compatability is wasteful since the app hasn't even begun to stabilize yet.

Once production-ready releases are being cut, support for older Android versions will be looked into. Working on that now would hinder development.
