### ISSUE TITLE
Hide Accrescent from the Installed and Apps Tab

### ISSUE THREAD

**Issue by Silther** [accrescent/accrescent#146]
This information should be displayed in the settings instead

**Comment by lberrymage** [comment]
How come?

**Comment by matchboxbananasynergy** [comment]
Regarding the "Apps" tab, I think it makes sense for Accrescent to be listed. After all, it's an app hosted on the Accrescent repository.

Correct me if I'm wrong, but F-Droid still appears in the F-Droid app itself as a listing, as does Play Store on Play Store.

The reason why you'd want that is so that you can update Accrescent if for whatever reason it doesn't automatically update itself (which it does), or to check the latest releases' changelog, which is a planned for all app listings etc.

Same thing applies to "Installed" apps. Accrescent is an app in the Accrescent repository, and you *do* have it installed on your device, so it makes sense to see it there.

Is there a specific reason why you think it doesn't make sense for it to be listed in those two places?

**Comment by PatrykMis** [comment]
One thing I think should be done is to remove/disable "open" button for Accrescent which is obviously already opened.

**Comment by lberrymage** [comment]
I agree, although that would be separate from this issue.

**Comment by Silther** [comment]
> Correct me if I'm wrong, but F-Droid still appears in the F-Droid app itself as a listing, as does Play Store on Play Store.

Right, I checked again later and it seems to be common practice in most app stores (the Google Playstore has its update function separately in the settings).
I just thought that it would make sense if Accrescent is not in a list of apps that are downloadable via Accrescent, to keep it separate when there are hundreds to thousands of apps later.

**Comment by lberrymage** [comment]
I'm going to close this for now since I don't see a concrete reason Accrescent shouldn't be listed and there are some benefits to listing it as @matchboxbananasynergy explained. I will disable the "open" button for Accrescent as @PatrykMis suggested though. If a specific reason for hiding Accrescent comes up, feel free to continue this thread.
