### ISSUE TITLE
Add app update blacklist 

### ISSUE THREAD

**Issue by ph00lt0** [accrescent/accrescent#154]
I would like the addition of an app blacklist. Apps in this list should not be updated through accrescent. 

The reason for this is that people might want to update certain apps through other sources and do not want to get prompted for updates from accrescent.

More background:
I use the Molly app (non FOSS). Accrescent prompted me for update. To me it was not clear this originated from accrescent, i am not sure the notification even tells. It did result in suddenly having the FOSS version installed while I require the non FOSS version for the features it has. This much to my annoyance. I understand Accrescent checks for the app id and Molly does not distinguish the app versions in form of an app id. Blacklisting would at least help me to not on every update having to find out I lost the features I need again.

**Comment by matchboxbananasynergy** [comment]
Molly's use case is peculiar because of their multiple app flavors with the same app IDs.

However, this isn't a feature that would only be implemented for Molly's use case. There are other valid reasons for why someone may want to get an app from a source other than Accrescent, even if that app is being published through it.
