### ISSUE TITLE
Aves does not update

### ISSUE THREAD

**Issue by Silther** [accrescent/accrescent#160]
I have installed Aves (v1.7.8) via Accrescent on two different systems (WSA and One UI 5.0).
Now, however, v1.7.9 has been released, but I cannot upgrade to it with Accrescent, even if I search for it manually in the Update tab.
Accrescent also shows v1.7.9 as the latest version.

**Comment by matchboxbananasynergy** [comment]
On my end, Accrescent has updated Aves Gallery to 1.7.9 without me having to do anything.

If you go to Settings > Apps > Aves Gallery, which app does it say it was installed from?

Also, what phone/OS/Android version are you using?

Does Accrescent have the "install from unknown sources" permission granted to it?

Are you able to install other apps through Accrescent at the moment?

**Comment by Silther** [comment]
> If you go to Settings > Apps > Aves Gallery, which app does it say it was installed from?

From Neo-Store via the IzzyDroid repo, so it should use the same signing key. (You were able to update Molly this way.)
Also Accrescent shows Aves Gallery in the ``installed`` tab.

> Also, what phone/OS/Android version are you using?

WSA running Android 12 & One UI 5.0 running Android 13

> Does Accrescent have the "install from unknown sources" permission granted to it?
> Are you able to install other apps through Accrescent at the moment?

Yes & yes

**Comment by matchboxbananasynergy** [comment]
>From Neo-Store via the IzzyDroid repo, so it should use the same signing key. (You were able to update Molly this way.)

Accrescent cannot update an app unless it is the installer of record. This goes for any app that uses the unattended update API.

You need to manually update it through Accrescent once, and once Accrescent is the installer of record (it will say it's installed by Accrescent instead of Neo Store), it will be able to install it without you doing anything going forward.

If you haven't updated through Neo Store at this point, you should be able to open Accrescent, go to Aves Gallery, tap on that, and click the update button.

**Comment by matchboxbananasynergy** [comment]
If you are not able to update it, I think you might not have the package from Izzy's repo, but from the main repo. There's a different flavor of Aves there now with a different app ID, but it used to be the same.

If that's the case, you have an app with the same app ID as the version published in F-Droid, but signed with F-Droid's key, and not the developer's.

The only way to update if that's the case is by uninstalling it and installing the Accrescent version.

**Comment by Silther** [comment]
> You need to manually update it through Accrescent once

That is the problem, I just can't.
It shows me in the ``installed`` tab that Aves v1.7.9 is already installed (which is wrong) and the ``update`` tab is empty.

**Comment by lberrymage** [comment]
> > You need to manually update it through Accrescent once
> 
> That is the problem, I just can't.
> It shows me in the ``installed`` tab that Aves v1.7.9 is already installed (which is wrong) and the ``update`` tab is empty.

Can you check the `versionCode` of your currently installed version of Aves?

**Comment by matchboxbananasynergy** [comment]
@xIUPITERx After chatting with lberrymage on Matrix, we figured it out.

The versionCode for Aves on Accrescent v1.7.9 is 89. The Izzy version's versionCode for v1.7.9 is 8901. You're not able to go from 8901 to 89, which is why you're unable to go from Izzy's version to Accrescent's version, even if the signatures match (which they should).

This is expected and not a bug in Accrescent. For those variants to be compatible with one another, the developer might have to adjust the versionCode for the Accrescent version going forward.

If the Accrescent version of Aves was on versionCode 8900 for 1.7.9, for example, the next version would be 9000, and the Izzy version you have would be 8901. You'd be able to go from 8901 to 9000, so you'd be able to update back and forth between versions.

For now, you'll have to uninstall it from Izzy's repo and re-install it from Accrescent.

**Comment by xIUPITERx** [comment]
> The versionCode for Aves on Accrescent v1.7.9 is 89. The Izzy version's versionCode for v1.7.9 is 8901. You're not able to go from 8901 to 89, which is why you're unable to go from Izzy's version to Accrescent's version, even if the signatures match (which they should).

So if I would wait for the next version ``1.7.10`` or ``1.8.0`` it should fix itself?

**Comment by matchboxbananasynergy** [comment]
> > The versionCode for Aves on Accrescent v1.7.9 is 89. The Izzy version's versionCode for v1.7.9 is 8901. You're not able to go from 8901 to 89, which is why you're unable to go from Izzy's version to Accrescent's version, even if the signatures match (which they should).
> 
> So if I would wait for the next version `1.7.10` or `1.8.0` it should fix itself?

It is not up to Accrescent to adjust the versionCode of the app, it can't do that. This could be fixed in a later version if the developer decided to change the versionCode for future versions of the Accrescent version. If they don't, it will continue to not be possible to jump from Izzy's version to the Accrescent version.

It hinges on the developer doing this. If you want to do this today, you'll have to uninstall and re-install the app.

**Comment by lberrymage** [comment]
> > The versionCode for Aves on Accrescent v1.7.9 is 89. The Izzy version's versionCode for v1.7.9 is 8901. You're not able to go from 8901 to 89, which is why you're unable to go from Izzy's version to Accrescent's version, even if the signatures match (which they should).
> 
> So if I would wait for the next version ``1.7.10`` or ``1.8.0`` it should fix itself?

No, because the Accrescent / Play Store variant versionCode would still be less than the GitHub/Izzy versionCode (90 opposed to 9001 etc.). Aves would need to change its versionCode scheme (append "00" or similar) for the variant published to Accrescent for that to happen.

**Comment by matchboxbananasynergy** [comment]
cc @deckerst

I was wondering whether this is intentional or not (not being able to go from Izzy -> Accrescent/Play Store) etc.

If not, it might make sense to apprend a "00" to the Accrescent and Play Store versions to allow for that transition, if it can be done.

Thanks!

**Comment by deckerst** [comment]
(haven't read the whole thread, just answering the latest post)

The app ID is the same for all flavours, except the `libre` one. But the package distributed via Play Store is signed by Google, so it's not the same signature as the one I use (for all packages on GitHub, Izzy, Accrescent...)

And another difference is that the package distributed by Izzy is an APK for the armeabi-v7a ABI only (because of package size limit), while Accrescent works with one APKS that works with everything.

**Comment by matchboxbananasynergy** [comment]
Thank you for your response!

The issue here isn't the app ID/signature, as it turns out, but rather the `versionCode` for each variant.

The Accrescent v1.7.9 versionCode is `89`, but the armeabi-v7a version that Izzy published has the versionCode `8901`. The v8a version that can be found on GitHub has the versionCode `8902`.

The apps have the same app ID and signature, so one can jump from the Accrescent version cause those match, plus the versionCode would be going from 89 to 8901 or 8902, so it works. If you're trying to go from Izzy's version to Accrescent, though, you're trying to go from vercionCode `8901` to `89` which isn't possible, cause it's seen as the package being downgraded.

If the versionCode for the Accrescent versionCode going forward had "00" appended to it (for example 8900, 9000 etc.), that would make it possible to jump between the Izzy version and Accrescent version, as the next version on Accrescent wouldn't have the versionCode 90, but `9000`, which would make it higher than `8901`, and thus someone would be able to update.

I hope I'm explaining this in a way that makes sense, thank you for your attention!

**Comment by lberrymage** [comment]
Note this isn't just the case for Accrescent, but also the Play Store, i.e., one can't go from the Izzy/GitHub variant to the Play Store variant.

**Comment by deckerst** [comment]
Oh, I see, thanks for the recap!

I don't intend to change the version code strategy. Ideally the actual code (`89`, `90` and so on) would be used everywhere, but not all stores can cope with the full APK/AAB. Anyway, users are expected to stick to a distribution channel. If they want to switch, it's not difficult to uninstall/reinstall. Aves also provides an export function for settings, and other customizations.

**Comment by matchboxbananasynergy** [comment]
> Oh, I see, thanks for the recap!
> 
> I don't intend to change the version code strategy. Ideally the actual code (`89`, `90` and so on) would be used everywhere, but not all stores can cope with the full APK/AAB. Anyway, users are expected to stick to a distribution channel. If they want to switch, it's not difficult to uninstall/reinstall. Aves also provides an export function for settings, and other customizations.

Thank you for elaborating! That's completely fine and understandable. I mostly just wanted to confirm whether this was intentional or not. Since it is intentional, we'll make sure to tell people looking to switch that they'll have to uninstall it and reinstall it.

Thanks again! :)

**Comment by matchboxbananasynergy** [comment]
@xIUPITERx Given the above, if you'd like to obtain Aves Gallery from Accrescent, you'll need to uninstall the version you're currently using, and install it from Accrescent.

Luckily, it seems that the app offers a way to backup your settings, so it shouldn't be too tedious to get everything set up the way you like it again!
