### ISSUE TITLE
Install Not working

### ISSUE THREAD

**Issue by S7venLights** [accrescent/accrescent#162]
I tried to install Aves Gallery and Molly, clicking install had no effect.

On the latest Github release.

**Comment by BHydden** [comment]
Did you wait a minute? There isn't a downloading progress bar yet but if you push it and wait it should install shortly.

**Comment by matchboxbananasynergy** [comment]
@S7venLights as BHydden said, there is no UI indication like a progress bar etc. just yet, so it will *feel* like nothing's happening until it actually downloads. If you keep pressing install because you think nothing is happening, the process will be delayed.

You should open the app, open the app and click "Install" once. If it's still not doing anything, ensure you've given the app the ability to install apps from unknown sources, and also clear its cache and try again.

**Comment by S7venLights** [comment]
Okay Works
