### ISSUE TITLE
Installation/Update progress indicator

### ISSUE THREAD

**Issue by Silther** [accrescent/accrescent#167]
https://user-images.githubusercontent.com/97352673/215037747-19a379f5-ad39-489a-939b-033e91d62d2a.mp4

Currently this is how an installation looks.

1. Pleass change the deactivated ``install`` button to a ``cancel download`` button.
2. If the download (and later the installation) is completed, show an pupup with: "Sucessfully downloaded (installed)".
3. Add an installation progress tracker after the user has confirmed the installation. (If it's not possible to get the installation progress, atleast show an indicator that something is happening).
4. 1-3 should also be displayed if it the update was started manuelly.

**Comment by matchboxbananasynergy** [comment]
1. An option to cancel the download is planned.
2. A notification? If so, is that really necessary?
3. Not sure if this is possible cause at that point the OS is handling the installation, though I could be wrong there.

**Comment by Silther** [comment]
2. Not necessarily a notification (although some would probably prefer it), but rather something like this:

https://user-images.githubusercontent.com/97352673/215072286-63ecf14b-3228-4e13-a961-7e21722b9fc7.mp4

**Comment by Silther** [comment]
3. It is not necessary to display the progress. Just an indication of whether something is happening at all would be enough.

**Comment by lberrymage** [comment]
@xIUPITERx These may all be good suggestions, but I'd ask that you create separate feature requests for each rather than putting them all in one issue so they can be discussed individually. In light of that, I'm going to close this issue, but feel free to create separate requests for each feature and/or mention them in the Matrix room so they can be tracked and discussed individually.
