### ISSUE TITLE
UI consideration, updates in 1 click.

### ISSUE THREAD

**Issue by S7venLights** [accrescent/accrescent#169]
I tried to add this to the ''update all button'' Issue. 
But it wouldn't let me. 
It would be nice have updates happen in as few clicks as possible. If the update all button was on every tab that could work. Alternatively if you could set the app to open by default on the updates tab. 

An update all button in a notification would be quicker still. 
Or Assuming there are unattended background updates… it would be nice to see a report back on what was updated when the app next open.

**Comment by S7venLights** [comment]
https://github.com/ImranR98/Obtainium

Has a unique and efficient layout which may be worth looking into. It also has a categories feature where you can sort apps according to custom groups.

**Comment by lberrymage** [comment]
Since there are quite a few ideas here, I'm going to close this in favor of https://github.com/accrescent/accrescent/issues/91, https://github.com/accrescent/accrescent/issues/157, and https://github.com/accrescent/meta/issues/4. But if there's something else not in the existing issues you'd like to suggest, please feel free to add comments to the corresponding issue or create a new issue for each suggestion as appropriate.
