### ISSUE TITLE
A more detailed description of the privacy rules of accepted apps

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#180]
For example, it is clear for an f-droid user that any app downloaded from their repo contains no trackers or propriatry libraries and dependancies.

What is Accrescent's policy in that respect? Do we have one? I couldn't find one in the app description.

What can I as an end user be guaranteed regarding the privacy of the apps in your repos?

While I have no reason to suspect any wrong-doing, I believe detailed information would not hurt.

**Comment by lberrymage** [comment]
I agree this needs to be more explicitly documented. To answer your immediate questions, Accrescent has no additional restrictions regarding proprietary code. Analytics/tracking are allowed "within reason and with reasonable consent." Since Accrescent is currently in alpha and only a select few developers can upload, there isn't yet a clear definition on what this entails.
