### ISSUE TITLE
Update manually does not work

### ISSUE THREAD

**Issue by Grkrz** [accrescent/accrescent#212]
Hi 
I am trying to manually update Molly but while downloading at about 80 % the Accrescent is shutting down. I have noticed it is not the first time that molly does not want to update. Last update went smooth.

**Comment by lberrymage** [comment]
Hi, can you clarify what exactly happens to Accrescent? Does it crash to the home screen, or does it freeze?

**Comment by Grkrz** [comment]
Hi it "jumps" to the home screen. I have tried many times. Closing the Accrescent, closing Molly, restarting the phone ,did not helped. 

I have tried now after around 3 hours and I succeed to update.

**Comment by matchboxbananasynergy** [comment]
For anyone else experiencing this, please try again now and let us know if it works.

**Comment by lberrymage** [comment]
Given there's been no further feedback, I think it safe to assume (as previously assessed) that the issue was simply a download timeout. Accrescent currently doesn't handle this gracefully, but I'm going to close this in favor of https://github.com/accrescent/accrescent/issues/10 since handling interrupted downloads is part of that feature.
