### ISSUE TITLE
Add SHA256 checksum for each Github apk release

### ISSUE THREAD

**Issue by serrq** [accrescent/accrescent#473]
This is the SHA256 for 0.18.0 apk (here on Github).

6146aead9214878e6192540bd0380a327179d452853f78842dc2c5f52cd69ba3

**Comment by lberrymage** [comment]
Can you explain why exactly this is wanted?

**Comment by serrq** [comment]
The checksum string allows a user to verify that the downloaded package is exactly the same after its trip over the internet (from server to client).

I use DeadHash to verify the app checksum.

https://github.com/CodeDead/DeadHash-android

**Comment by rusty-snake** [comment]
I guess a corrupted apk due to network errors can not be installed anyway.

**Comment by lberrymage** [comment]
> The checksum string allows a user to verify that the downloaded package is exactly the same after its trip over the internet (from server to client).
> 
> I use DeadHash to verify the app checksum.
> 
> https://github.com/CodeDead/DeadHash-android

I don't think this covers anything not already covered by APK signatures. There's no need to separately verify the checksum of the APK in the case of accidental corruption since the APK's signature won't verify and install in that case, and in the case of malicious tampering, we already publish Accrescent's signing certificate hash [on other channels](https://accrescent.app/faq#verifying).

Does that cover your use case, or is there something else I'm not thinking of?

**Comment by serrq** [comment]
I cannot verifying a package signature because I am not a developer.

**Comment by lberrymage** [comment]
I know it's an advanced use case, but the process is explained on the website, and there are easier methods e.g. [AppVerifier](https://github.com/soupslurpr/AppVerifier) if you trust those sources (this is not an endorsement of that app).

But verifying a SHA256 hash obtained from the same source as the APK itself (in this case, GitHub) doesn't protect against malicious tampering because the attacker could presumably tamper with the SHA256 hash as well.

**Comment by serrq** [comment]
Might you building an apk to make things easy for the laymen?

**Comment by lberrymage** [comment]
I'm sorry, I'm not quite sure what you're asking.

**Comment by serrq** [comment]
An android app to verify apk signature easily (with GUI).

**Comment by BHydden** [comment]
That is what AppVerifier does,  which was linked above.

**Comment by serrq** [comment]
> That is what AppVerifier does, which was linked above.

It needs to trust it. Trust less solutions?

**Comment by BHydden** [comment]
There is always trust somewhere down the line. Whether you trust Accrescent or AppVerifier or some other app,  there is no avoiding TOFU.

**Comment by rusty-snake** [comment]
If "insert name here" makes an app for it , rather you do it all by yourself you have to trust "name".

**Comment by serrq** [comment]
Mmm I am not native English. Might you explaining it with other words? I don't understand.

**Comment by PatrykMis** [comment]
I believe there is no need for including SHA256 checksum of the app. The APK certificates can be validated in other apps like e.g. [Package Manager](https://github.com/SmartPack/PackageManager) and/or probably [App Manager](https://github.com/MuntashirAkon/AppManager). Validating certificates, especially for v3 or v4 signed APKs is more trustworthy than just SHA256.

If I have said something wrong here then sorry in advance.
