### ISSUE TITLE
Request explanation about two permissions

### ISSUE THREAD

**Issue by serrq** [accrescent/accrescent#476]
I don't understand these permissions.

Why your app should installing apps "without user interaction" ?

![1000108714](https://github.com/accrescent/accrescent/assets/113377431/8e497540-79d6-42d3-b78c-a6fbaab21e9e)

**Comment by matchboxbananasynergy** [comment]
To explain ENFORCE_UPDATE_OWNERSHIP, I will give you an example.

Let's say you have both F-Droid and Accrescent installed, as an example, and the same app exists on both respective app stores.

If you install that app from Accrescent, and there's a new update for that app, enforcing update ownership means that F-Droid shouldn't bug you updating that app, because Accrescent is already taking care of it. You can of course always override this by updating the app from the other store manually, but having this avoids multiple stores "competing" to update the same app, instead of the app store you installed it from being responsible for updating that app.

>Why your app should installing apps "without user interaction" ?

That's not what it says. It says **update** app without user interaction, not install. Regular sandboxed apps **cannot** install apps without user interaction. However, if you have already manually installed an app, and a specific app store is the installer of record, it can update the app without user interaction. This has been possible since Android 12.

If you don't want that behavior, you can turn it off in Accrescent's settings by toggling off the "Automatic updates" toggle.

**Comment by serrq** [comment]
Ok thanks. I disabled the second one (toggle), but I haven't control over the first one.

About it I haven't nothing against the app store "competition" for an update.

**Comment by matchboxbananasynergy** [comment]
There doesn't have to be a toggle about that. If at any point you want to switch from Accrescent handling updates for a specific app to another store doing so, all you have to do is update the app from the other store, and that store will become the new installer of record, and will be the one handling updates for that app going forward.

This doesn't matter much if you're manually updating, regardless.

**Comment by rusty-snake** [comment]
> About it I haven't nothing against the app store "competition" for an update.

Well. Let's assume you have an App foo (appid is `com.example.foo`). This app is available as flavour left in Accrescent (versionCode `25`) and flavour right on IzzyOnDroid (from GitHub Release) with versionCode `1025` and same signing key. You install this app from Accrescent. Then version `26`/`1026` gets release and your f-droid client wins the "competition" (the update is successful because it is a higher versionCode and has the same appid with same signing key). Now `27`/`1027` gets releases. A new feature added a huge dependency and it is now to big for IzzyOnDroid repo so it gets removed from there. Then `28`/`1028` gets releases which fixes an critical vulnerability. You won't get this update.

**Comment by serrq** [comment]
@rusty-snake Nobody stops me from uninstalling the (Izzy) app and switching to a new source. This has happened before with KeepassXD. Updates on Fdroid were blocked and I had to switch to Izzy (having to uninstall the fdroid app and reinstall it from the Izzy side).

I think that permission is useless, at least to me.
Of course I say this after reading the reasons you have given.

But okay, in some cases it can be useful.
I understand your point of view.

**Comment by rusty-snake** [comment]
Of course you can reinstall (if the app provides export/import feature). But how do you notice that you have to do this?

Summary (from me):  A "primary source" for an app avoids some trouble.
And manual switching is always possible.
