### ISSUE TITLE
Add support for installing variants of apps with the same App ID.

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#562]
Accrescent should be able to handle installing  variants of apps that have the same app ID. For example, Molly has 3 different versions (FOSS, non-FOSS and UP) all with the same app ID of `im.molly.app`. Since Accrescent does not support this, only one version (FOSS) is available for download.

**Comment by matchboxbananasynergy** [comment]
This is likely not something that will be supported in Accrescent as it's not technically the correct way to handle app variants. As far as I can tell, it sounds like the path that Accrescent will eventually take is to offer the ability for apps to have feature modules, so parts of an app can be downloaded depending on what people want, which is the "correct" way to do this.

**Comment by ghost** [comment]
Forgot you were a moderator for Molly too haha. Thanks for your answers. Should this issue be closed?

**Comment by matchboxbananasynergy** [comment]
I'll let Logan elaborate with his thoughts on this as well. :)

**Comment by lberrymage** [comment]
What @matchboxbananasynergy is correct. The supported methods to have different variants of the same app in Accrescent are 1) submitting separate apps with different app IDs and (eventually) 2) dynamic feature modules. Both of these methods are facilitated by the OS.

Accrescent supporting multiple variants with the same app ID would be an additional dimension of differentiating apps which isn't recognized by the OS, which sprouts various new problems that would need to be solved to make that feature work. Because of this, I don't see a compelling reason to support a third method of distinguishing variants which isn't supported by the OS or [Google documentation](https://developer.android.com/build/build-variants) like the other two are.

If there's a compelling reason I'm not aware of, I'm still open to the idea, but as of now it seems like this feature would be more trouble than it's worth.
