### ISSUE TITLE
Add GitHub `CODEOWNERS` file for translations 

### ISSUE THREAD

**Issue by mainrs** [accrescent/accrescent#59]
Hello!

GitHub supports a [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file that makes it possible to get notified if certain files within a repository change. I'd like to propose to add a new GitHub team for translators and make it the owner of files like `app/src/main/res/values/strings.xml`. This way people in the team get notified if new strings get added and can accordingly prepare new PRs updating the language files.

The only downside I see is that people get notified by getting assigned to a PR as a reviewer if code-owner files change. It does not work if one pushes directly on a branch AFAIK.

I'd be willing to set this up if you see it as low priority or don't have the time. I have a language PR prepared as well alongside the already existing #58.

Cheers.

P.S.: How can one help with the project in the long-term? I am looking to contribute once I have more time, which would be around October. Can I simply fix/implement features? Or is it better to ask around the matrix room?

**Comment by lberrymage** [comment]
Seems pretty reasonable to me. I just have a few concerns. From the docs:

> When the code owner is a team, that team must be visible and it must have write permissions...

and I'd rather not give others write access to the repository, at least not yet. That's an implementation detail though and it might be possible to satisfy that requirement while giving each team member read-only access (if not, then CODEOWNERS can have individuals). We'd need to mess with it.

Secondly,

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

So every translator for every language would have a review requested for changes to `app/src/main/res/values/strings.xml` as opposed to just being notified. Maybe that's desirable so translators can add translations for new string resources before they're merged, but I'm not too worried about having temporarily out-of-date translations and I don't see that approach scaling well at this stage. Making translators owners of `app/src/main/res/values-<lang>/strings.xml` might be more appropriate.

Thirdly, I would need to make a pull request instead of pushing directly whenever I update `app/src/main/res/values/strings.xml` which isn't that big of a deal but I might forget. That wouldn't be a problem if we go with approach I mentioned above instead.

Lastly, @Wonderfall @Ilithy, would you be interested in being added to a CODEOWNERS and do you have any other input on how you'd like to see this process work?

**Comment by lberrymage** [comment]
> P.S.: How can one help with the project in the long-term? I am looking to contribute once I have more time, which would be around October. Can I simply fix/implement features? Or is it better to ask around the matrix room?

First of all, thanks for your interest in contributing :). You could start by looking at the roadmap at https://github.com/orgs/accrescent/projects/2 if you want to look through what's definitely wanted, but feel free to fix other bugs you know about or suggest features that we haven't thought of yet. The Matrix room is great for more real-time chat if you want to discuss this topic more thoroughly, ask more questions, run features by people before implementing them, etc.

**Comment by Ilithy** [comment]
Hi, my apologies for the delay of my response, yes, this seems smart;
in the case of @Wonderfall I don't think it is useful (he is the proofreader in French, so he is necessarily informed by me, or @lberrymage of an update of the files.
In my case, working under the supervision of @Wonderfall, I would do with him the modifications on our repo, and push to yours once the verifications by @Wonderfall done (instead of doing all this during the PR), If you both agree with this method

**Comment by mainrs** [comment]
I know there are a lot of open-source (self-)hosted translations platforms out there. It might be better to go that route and choose a platform that makes it easy to contribute translations. For example being able to login via GitHub OAuth.

For the long-run it might be a better option to not use `CODEOWNERS` (after giving it some thought :)).

**Comment by Ilithy** [comment]
Ok ^_*
Thinking of _(Hosted)_ Weblate?
Because Crowdin requests access to all the repositories of the user (the developer/owner) public and private etc...not sure that @lberrymage wants to.
but these methods are indeed easier for some users (although some prefer to perform PR)

**Comment by lberrymage** [comment]
I was looking at hosted Weblate before but found their pricing off-putting. Looking into it again, however, it looks like we're eligible for their Libre plan which would give us free access to their advanced tier since Accrescent is open-source.

I'll apply for it just so we have it as an option. In the meantime, let me know what you think of Weblate if you're doing or interested in doing translations. I don't do translation work so I'm not familiar with the pros and cons of each solution (although Weblate seems to be pretty widely used among open-source projects).

> Because Crowdin requests access to all the repositories of the user (the developer/owner) public and private etc...not sure that @lberrymage wants to.

Thankfully GitHub allows for granting access on a per-repository basis. Read access is obviously fine, but I don't want to give another service write access to any of the project's repos. Not sure which one Crowdin asks for.

**Comment by Ilithy** [comment]
I'm using Weblate (as a translator), my opinion and it's easy to use, allows login using these github credentials (or many others), so that's pretty positive.
Crowdin has a much neater interface and a notch more convenient, but the difference isn't monstrous either.
If Weblate suits you (in free), it should suit the majority of translators (others can do PR).

> Not sure which one Crowdin asks for.

I must be honest, I don't know.

**Comment by mainrs** [comment]
I have been using weblate as a translator as well and I found it good. It's easy to understand. There are more "luxurious" solutions but they often are attached to a price tag.

**Comment by lberrymage** [comment]
Alright, I've gotten Hosted Weblate set up (https://hosted.weblate.org/projects/accrescent/#languages) and have submitted a request for the Libre plan.

I'm not very familiar with Weblate and I haven't gone through the settings extensively so let me know if a setting isn't as you expect or is getting in your way. I want to make this usable for you all so feel free to make suggestions.

We can consider submitting translations with Weblate as experimental at this point.

cc https://github.com/accrescent/meta/issues/5

**Comment by lberrymage** [comment]
Since we have an alternative to `CODEOWNERS` for translations in place I'm going to close this issue and direct further discussion about translation management to https://github.com/accrescent/meta/issues/5.

**Comment by mainrs** [comment]
Thanks for setting everything up!

**Comment by lberrymage** [comment]
Thanks for the suggestions!
