### ISSUE TITLE
Question about Apps on Accrescent

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#626]
Is a App on Accrescent more secure than a App on Github? For example I was wondering: Organic Maps Web Build APK on Github vs Accrescent Google Play compatible APK? Is a App in your Store more secure, because you check it too? Is it more secure, because now more People who have knowledge check it too? Vs only Github published APK which only is checked by the Developer.

It would be really interesting to know!

**Comment by lberrymage** [comment]
An app itself is not inherently more or less secure by being on Accrescent. Accrescent does not and cannot guarantee that its apps don't contain malicious code; you still have to trust the developer. However, all else being equal, Accrescent does ensure that even if its servers are compromised, you can't be served a malicious counterfeit for the initial installation. GitHub on the other hand, if compromised, could serve a malicious copy for the initial install. But in both cases, you can't accidentally update to a malicious copy if your initial installation was legitimate because Android will verify that the signing key is the same.

Accrescent also has app [privacy and security requirements](https://accrescent.app/docs/guide/appendix/requirements.html) which are often more strict than those of other stores, so in some cases, a variant published to Accrescent may be more private and/or secure than variants published elsewhere. For example, an app which includes an accessibility service for autofill wouldn't be allowed in Accrescent, so it may be published to Accrescent without that feature enabled.

**Comment by ghost** [comment]
Okay thank you so much for this helpful reply! I appreciate all of your amazing work!
