### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#627]
Hey,

i saw that the App has Target SDK on 35 and Minimum SDK on 29 and I wanted to ask if you could make Minimum SDK to 31? I would appreciate that!

**Comment by rusty-snake** [comment]
Can you explain why a higher min-sdk is better?

**Comment by ghost** [comment]
A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better.

**Comment by PatrykMis** [comment]
I think I understand @Jeffrey2307's perspective: Android 12 (SDK 31) is the last version that receives security patches. Furthermore, the lower the `minSdk`, the more internal compatibility layers and techniques are required. For example, lower SDK versions need v1/v2 signing, have different optimization levels, and so on.

**Comment by rusty-snake** [comment]
Ok, so it is not only about raising a number in a build file but also to drop compatibility code etc.

**Comment by ghost** [comment]
It is recommended. For example GrapheneOS uses for the App Store Minimum SDK 31. It makes the work easier.

**Comment by PatrykMis** [comment]
@Jeffrey2307 It’s very unlikely that @lberrymage would resign from this. Take a look at the changelog, especially [v0.13.0](https://github.com/accrescent/accrescent/releases/tag/0.13.0). Support was added for Android 10 and 11 (SDK 29 and 30, respectively), though it's something I'd like to see from Accrescent as well. This approach encourages users to rely on a more secure infrastructure, as older Android releases only receive critical and high-severity patches.

**Comment by ghost** [comment]
@PatrykMis We never know. Let's see.

**Comment by lberrymage** [comment]
I don't plan on increasing the minimum SDK for now since it's not currently causing issues and it isn't much work to maintain support for Android 10 and 11. I agree that supported Android versions should be prioritized; however, existing users on Android 10 and 11 devices expect Accrescent to continue working, and it's not trivial for people to get a new device. I'll increase it once it becomes a burden to maintain. For what it's worth, I don't plan on adding support for Android versions lower than 10 (I forget exactly why, but it's significantly more work to support those).
