### ISSUE TITLE
Remove Qlango until an opensource tag exists

### ISSUE THREAD

**Issue by boredsquirrel** [accrescent/accrescent#637]
Accrescent presents itself as a privacy and security focused appstore.

Which is technically very true, but many people expect that this also includes the apps in there. If you are such a trusted store, people trust in your judgement too.

The store has no metadata at all, apart from the App icon
- screenshots / pictures
- description
- link to source
- link to website
- app author
- tags (like the `opensource` one)
- list of trackers; dependency on known invasive components like play services, huawei, amazon

There is no warning that Qlango is a proprietary app, includes known tracking libraries and requires a Google Account to work.

![](https://tux.social/system/media_attachments/files/113/520/413/915/209/438/original/7ab179e1ec1a4186.jpg)

Please add a warning, or at least something to identify this app as very different from the others, or remove it (temporarily).

Thanks!

**Comment by rusty-snake** [comment]
AFAICTY both, "Organic Maps" and "Aves Gallery" (the not Libre flavour), contain proprietary client libraries. Should the be removed/warned too?

**Comment by boredsquirrel** [comment]
@rusty-snake Aves has a libre variant, not sure about Organic Maps

Molly for example is the FOSS variant afaik

**Comment by lberrymage** [comment]
Accrescent doesn't claim to serve only open-source apps and [never has](https://github.com/accrescent/website/commit/58bf1a7ca0f14005ba315dc07f639fdd75ba09bd#diff-a9380e533555552687e143dcafc3acd4487336aa809d406ce7a874e55b4f05c5R144) out of the belief that an app's source model doesn't inherently make it more or less private or secure. Qlango doesn't violate any explicit or implicit Accrescent policy by the properties you listed, so it would be inappropriate to remove it.

There are plans to add labels for open-source apps and those which require / include in-app purchases. However, the architecture for adding these features in a future-proof way does not yet exist, so there are no plans to expedite them.

In addition, "trackers" are subjective. Accrescent has no plans to enumerate specific libraries or classes and blacklist them solely based on the fact that they connect to Google, Amazon, etc.; collect analytics; or contain proprietary code. This approach isn't scalable anyway because it is trivial to bypass such detection methods.

If you have suggestions to specific Accrescent policy, please make them at https://github.com/accrescent/meta, but existing apps will not be de-listed or negatively labeled against documented policy except in exceptional circumstances because app developers depend on those policies.

**Comment by boredsquirrel** [comment]
*For ease of reading I would answer a few points here and then move to the meta issuetracker*

> an app's source model doesn't inherently make it more or less private or secure.

Just seeing how badly written kernel blobs, Winamp code and a ton apps are (like the Sennheiser app, 500MB, or various onlineshops that refuse to just use the webview)...

I would say while of course it doesn't ***inherently*** affect the quality and intentions of the code, in reality apps that just throw in a bunch of proprietary libraries by big tech will ***often*** contain code written for malicious purposes, like a payment library that also collects analytics data.

This is a business and big tech is using their market dominance and tricks, to always embed tracking everywhere.

So while factually your statement is correct, I find it misleading when being in a realistic scenario, like that which your Appstore presents.

> adding these features in a future-proof way 

Mind explaining what needs to be future-proof here? Metadata can always be updated, right?

 > "trackers" are subjective.

Well we could argue about useful and privacy preserving metadata here. But that is it. Every metrics collected and sent to a server that don't serve the improvement of this product's features.

For example, improving Googles Ad Network by collecting typed words with GBoard (or Microsofts with Swiftkey, ...) would not count as it improves 1. another product 2. features that you dont use the app for.

> This approach isn't scalable anyway because it is trivial to bypass such detection methods.

You expect that your labelling will care Google, Amazon and Meta? F-Droid exists for a decade or so and clearly lists trackers, but yeah maybe the devs care and would try to circumvent it. I have never seen this though, and Exodus and NeoStore etc exist. But yeah, maybe when you become a big and interesting target.

**Comment by lberrymage** [comment]
> Just seeing how badly written kernel blobs, Winamp code and a ton apps are (like the Sennheiser app, 500MB, or various onlineshops that refuse to just use the webview)...
>
> I would say while of course it doesn't inherently affect the quality and intentions of the code, in reality apps that just throw in a bunch of proprietary libraries by big tech will often contain code written for malicious purposes, like a payment library that also collects analytics data.

I understand your perspective, but I'm not really interested in arguing this point. There are a lot of poorly written open source apps as well, and anecdotal evidence isn't sufficient to change Accrescent's policy. Regardless, Accrescent chooses to provide an opportunity for developers to upload apps without restricting source code licensing models, and there are no plans for this to change. It also doesn't consider basic analytics to be malicious, and there are no plans for this to change either.

> Mind explaining what needs to be future-proof here? Metadata can always be updated, right?

The repository metadata is currently undergoing a major overhaul, so any new fields would need to be re-implemented in the new system if implemented now, potentially doubling the implementation cost. The current system is difficult to maintain as far as preventing breaking changes from sneaking in, which is part of the reason for the overhaul. Thus, changes to store metadata are on hold until the overhaul is complete.

> You expect that your labelling will care Google, Amazon and Meta? F-Droid exists for a decade or so and clearly lists trackers, but yeah maybe the devs care and would try to circumvent it. I have never seen this though, and Exodus and NeoStore etc exist. But yeah, maybe when you become a big and interesting target.

My point isn't whether people are actively circumventing it but rather whether they can, e.g., an unlocked gate is as useful as no gate as soon as someone tries to open it. Accrescent aims to enforce objective and verifiable security and privacy properties, but enumerating "tracker" libraries is fundamentally subjective and cannot consistently provide any concrete guarantees. It also doesn't require malicious intent to circumvent. For example, using an internal analytics library which isn't yet on the well-known "tracker" lists would bypass a check. Blacklisting isn't a helpful or maintainable approach to security in most cases. Again, regardless, I don't see blacklisting analytics etc. libraries as a useful target for Accrescent's goals.

Since blacklisting specific libraries or limiting proprietary code on the platform isn't consistent with Accrescent's goals, Accrescent's approach to such is unlikely to change.

**Comment by wvholst** [comment]
> In addition, "trackers" are subjective. Accrescent has no plans to enumerate specific libraries or classes and blacklist them solely based on the fact that they connect to Google, Amazon, etc.; collect analytics; or contain proprietary code. This approach isn't scalable anyway because it is trivial to bypass such detection methods.
> 

If you consider "trackers" to be subjective, then your claim of being privacy-focused is false advertising.

**Comment by lberrymage** [comment]
@wvholst What would you consider objective markers of a tracker? I've laid out reasons existing methods are subjective. I'm interested in hearing alternatives to auditing permissions as Accrescent does now, but saying we're engaging in false advertising isn't helpful.

**Comment by DantesNoWar** [comment]
Thanks for this interesting discussion; I have all my answers solved and have decided to move away from Accrescent since it doesn't serve my privacy needs.
It's sad to read certain statements in a so-called "privacy-focused" project.
Surely reporting a lot, but not all the latest, of trackers is better than not reporting anything at all. Period.
