### ISSUE TITLE
Add version info to Settings?

### ISSUE THREAD

**Issue by Johnny5sword** [accrescent/accrescent#98]
It will be also a link to the source code. When the user clicks it, it would be opened by the default browser of Android. 
This is can be found in [Droid-ify](https://github.com/Iamlooker/Droid-ify) (F-Droid client) and also other apps.

<img src="https://user-images.githubusercontent.com/112535244/190979944-2ae27518-ea7c-471e-8d5d-f7c81dd99253.png" width="200" height="450" /> 

Hi! My reason for wanting this is every time accrescent updates, I have to type and search accrescent GitHub to check the changelogs. With this, it's just one tap away.

**Comment by lberrymage** [comment]
Thanks for the suggestion!

This solution tries to do three separate things:

- add a link to Accrescent's source code from the app
- add an easy way to view Accrescent's changelog from the app
- add a way to view the installed version of Accrescent in-app

I like the idea of all of these features, but I'm not sure this is the best way to implement them because it's not immediately obvious from the button you describe that it links to something. Perhaps a button that explicitly says "Source code" and links to the source would be more appropriate?

Regarding the second feature, I've created a [separate issue](https://github.com/accrescent/meta/issues/12) for viewing changelogs in-app. For the third, you can already view Accrescent's version from its app detail screen.

**Comment by Johnny5sword** [comment]
Ah yes, that's right. It would be more descriptive/user-friendly if there's a button that shows "Source code" instead of being like an Easter egg.

About the version info from the app detail screen, that's new to me. Thanks!
